# Data source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    initialization-mode: always

# Database
  database:
    driverClassName: org.postgresql.Driver

# Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false

# JPA
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true

# Server
server:
  port: 8080

# Swagger
springdoc:
  swagger-ui:
    operations-sorter: alpha